Spring:
  Datasource:
    url: jdbc:mysql://localhost:3306/ALKEMYLABS?serverTimezone=UTC
    username: root


  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      driverClassName: com.mysql.cj.jdbc.Drive
    database: mysql
